print ("Content-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>Python CGI</title>')
print ('</head>')
print ('<body>')
print ('<h2>Python CGI</h2>')
print ('<p>')
for i in range(0, 10):
	print ("hello world ", end='')
	print (i)
	print ('<br>')
print ('<p>')
print ('</body>')
print ('</html>')
